---
- name: Install postgres
  ansible.builtin.apt:
    name:
      - postgresql
    state: present

- name: Install Zabbix repo
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu24.04_all.deb"

- name: Install Zabbix packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - zabbix-web-service
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php8.3-pgsql
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - zabbix-agent
    state: present

- name: Create user postgresql
  ansible.builtin.expect:
    command: sudo -u postgres createuser --pwprompt zabbix
    responses:
      (?i).*(Enter password for new role)(.*):
      - '{{ password_db }}'
      (?i).*(Enter it again)(.*):
      - '{{ password_db }}'
  ignore_errors: true

- name: Create db postgresql
  ansible.builtin.shell:
    cmd: sudo -u postgres createdb -O zabbix zabbix
  ignore_errors: true

- name: Unpack schema
  ansible.builtin.command:
    cmd: gunzip -k /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
    creates: /usr/share/zabbix-sql-scripts/postgresql/server.sql

- name: Import schema
  ansible.builtin.shell:
    cmd: sudo -u zabbix psql zabbix -f /usr/share/zabbix-sql-scripts/postgresql/server.sql

- name: Copy server conf file
  ansible.builtin.template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: '0600'
    backup: true

- name: Copy nginx conf file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/zabbix/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Enabled and restart Zabbix
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - zabbix-server
    - zabbix-agent
    - nginx
    - php8.3-fpm
