---
- name: Install filebeat
  ansible.builtin.apt:
    deb: "https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.18.1-amd64.deb"

- name: Copy conf file
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    backup: true

- name: Enable and restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    enabled: true
    daemon_reload: true
    state: restarted

- name: Enable modules
  ansible.builtin.shell: filebeat modules enable nginx
